name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on each push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 1# Checkout Repository
      uses: actions/checkout@v3

    - name: 2# Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.10.5

    - name: 3# Install Dependencies
      run: flutter pub get

